apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduled-woop.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.monitoring.prometheusAnnotations }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: {{ .Values.observability.port | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: scheduled-woop
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: scheduled-woop
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.observability.port }}
      targetPort: metrics
      protocol: TCP
